import Script from "next/script";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          id="apple-pay-sdk"
          src="https://applepay.cdn-apple.com/jsapi/1.latest/apple-pay-sdk.js"
          strategy="afterInteractive"
          crossOrigin="anonymous"
          // onError={(e) => {
          //   console.error("Failed to load Apple Pay SDK:", e);
          // }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
